version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
        time: "02:00"
    target-branch: "main"
    commit-message:
      prefix: "deps(ci)"

  # Codebase
  ## Go dependencies
  - package-ecosystem: "gomod"
    directory: "/provd"
    schedule:
        interval: "daily"
        time: "02:00"
    target-branch: "main"
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: "gomod"
    directory: "/provd/tools"
    schedule:
        interval: "daily"
        time: "02:00"
    target-branch: "main"
    commit-message:
      prefix: "deps(go-tools)"

  ## Subiquity dependencies
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: "daily"
        time: "02:00"
    target-branch: "main"
    commit-message:
      prefix: "deps(subiquity)"
    allow:
      - dependency-name: packages/subiquity_client/subiquity
        dependency-type: direct:production
