name: ubuntu_wizard
description: Shared library for Ubuntu wizards.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  ubuntu_flavor: ^0.3.0
  ubuntu_localizations: ^0.3.5
  ubuntu_widgets: ^0.3.3
  wizard_router: ^1.1.0
  yaru: 1.2.1
  yaru_widgets: 3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.0
  ubuntu_test: ^0.1.0-beta.8
  yaru_test: ^0.1.5
