name: ubuntu_provision
description: Shared package for Ubuntu provision.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  collection: ^1.17.0
  dbus: ^0.7.10
  diacritic: ^0.1.5
  file: ^6.1.4
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.1
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  gsettings: ^0.2.8
  json_annotation: ^4.8.1
  meta: ^1.10.0
  nm: ^0.5.0
  path: ^1.8.3
  platform: ^3.1.2
  safe_change_notifier: ^0.3.2
  stdlibc: ^0.1.4
  subiquity_client: ^0.1.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: 5af6896c75b5ab8f78b93f7f358836a8c4c7857f
  ubuntu_flavor: ^0.2.2
  ubuntu_localizations: ^0.3.5
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.1
  ubuntu_session: ^0.0.4
  ubuntu_utils: ^0.1.0
  ubuntu_widgets: ^0.3.3
  ubuntu_wizard: ^0.1.0
  udev: ^0.0.3
  upower: ^0.7.0
  xdg_directories: ^1.0.4
  yaml: ^3.1.2
  yaru: 1.2.1
  yaru_icons: ^2.4.0
  yaru_widgets: 3.4.0
  yaru_window: 0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: 5.4.4
  ubuntu_lints: ^0.3.0
  ubuntu_test: ^0.1.0-beta.8
  yaru_test: ^0.1.5

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/theme/
