name: ubuntu_provision
description: Shared package for Ubuntu provision.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.2"

dependencies:
  collection: ^1.17.0
  dbus: ^0.7.10
  diacritic: ^0.1.5
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  gsettings: ^0.2.8
  intl: ^0.18.1
  meta: ^1.11.0
  nm: ^0.5.0
  path: ^1.8.3
  pdfrx: ^1.0.52
  platform: ^3.1.2
  safe_change_notifier: ^0.3.2
  stdlibc: ^0.1.4
  subiquity_client: ^0.1.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: ubuntu/noble
  ubuntu_flavor: ^0.4.0
  ubuntu_localizations: ^0.3.5
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.1
  ubuntu_session: ^0.0.4
  ubuntu_utils: ^0.1.0
  ubuntu_widgets: ^0.5.5
  ubuntu_wizard: ^0.1.0
  udev: ^0.0.3
  upower: ^0.7.0
  url_launcher: ^6.2.5
  yaml: ^3.1.2
  yaru: 4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: 5.4.4
  translations_cleaner: ^0.0.5
  ubuntu_lints: ^0.3.0
  ubuntu_test: ^0.1.0-beta.8
  vector_graphics: ^1.1.11
  yaru_test: ^0.1.6

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/theme/
