name: factory_reset_tools
description: "Tools for preinstalled systems for creating Reset Media and to reboot into a Reset Partition"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.1"

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  collection: ^1.17.0
  dbus: ^0.7.10
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  handy_window: ^0.4.0
  intl: ^0.20.2
  meta: ^1.11.0
  path: ^1.8.3
  retry: ^3.1.2
  ubuntu_localizations: ^0.5.2+2
  ubuntu_utils: ^0.1.0
  ubuntu_wizard: ^0.1.0
  yaml: ^3.1.2
  yaru: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
