name: ubuntu_provision_test
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.2"

dependencies:
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  flutter_test:
    sdk: flutter
  gsettings: ^0.2.8
  provd_client:
    path: ../provd_client
  subiquity_client: ^0.1.0
  ubuntu_bootstrap: ^0.1.0
  ubuntu_flavor: ^0.4.0
  ubuntu_init: ^0.1.0
  ubuntu_provision: ^0.1.0
  ubuntu_service: ^0.3.1
  ubuntu_test: ^0.2.2
  ubuntu_utils: ^0.1.0
  ubuntu_wizard: ^0.1.0
  yaru: ^5.3.0
  yaru_test: ^0.2.0

dev_dependencies:
  ubuntu_lints: ^0.4.0
