name: ubuntu_provision_test
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  dbus: ^0.7.3
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.13.0
  flutter_test:
    sdk: flutter
  gsettings: ^0.2.7
  sysmetrics:
    path: ../sysmetrics
  ubuntu_bootstrap:
    path: ../ubuntu_bootstrap
  ubuntu_flavor: ^0.2.0
  ubuntu_init:
    path: ../ubuntu_init
  ubuntu_provision:
    path: ../ubuntu_provision
  ubuntu_service: ^0.2.2
  ubuntu_test: ^0.1.0-0
  ubuntu_utils:
    path: ../ubuntu_utils
  ubuntu_wizard:
    path: ../ubuntu_wizard
  yaru: ^1.1.0
  yaru_test: ^0.1.3
  yaru_widgets: ^3.2.0
