name: ubuntu_provision_test
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  dbus: ^0.7.8
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  flutter_test:
    sdk: flutter
  gsettings: ^0.2.8
  sysmetrics: ^0.1.0
  ubuntu_bootstrap: ^0.1.0
  ubuntu_flavor: ^0.2.0
  ubuntu_init: ^0.1.0
  ubuntu_provision: ^0.1.0
  ubuntu_service:
    git:
      url: https://github.com/spydon/ubuntu-flutter-plugins.git
      ref: ubuntu_service/param-generics
      path: packages/ubuntu_service
  ubuntu_test: ^0.1.0-0
  ubuntu_utils: ^0.1.0
  ubuntu_wizard: ^0.1.0
  yaru: ^1.1.0
  yaru_test: ^0.1.3
  yaru_widgets: ^3.2.2

dev_dependencies:
  ubuntu_lints: ^0.1.0
