name: provd_client
description: Dart client for interacting with provd
repository: https://github.com/canonical/ubuntu-desktop-provision/packages/provd_client
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fixnum: ^1.1.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  grpc: ^3.2.4
  meta: ^1.10.0
  protobuf: ^3.1.0
  protoc_plugin: ^21.1.2

dev_dependencies:
  build_runner: ^2.4.7
  mockito: 5.4.4
  test: any
  ubuntu_lints: ^0.3.0