name: ubuntu_init
description: Ubuntu Init
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.1"

dependencies:
  args: ^2.4.2
  barcode_widget: ^2.0.4
  collection: ^1.17.0
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  form_field_validator: ^1.1.0
  gsettings: ^0.2.8
  handy_window: ^0.4.0
  intl: ^0.20.2
  meta: ^1.11.0
  path: ^1.8.3
  provd_client: ^0.1.0
  stdlibc: ^0.1.4
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: 82318b76081ed09db8351a055f11f63b70b7eaa4
  ubuntu_flavor: ^0.4.0
  ubuntu_localizations: ^0.5.2+2
  ubuntu_logger: ^0.1.1
  ubuntu_provision: ^0.1.0
  ubuntu_service: ^0.3.1
  ubuntu_session: ^0.0.4
  ubuntu_utils: ^0.1.0
  ubuntu_widgets: ^0.7.3
  ubuntu_wizard: ^0.1.0
  yaru: 8.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.4
  translations_cleaner: ^0.0.5
  ubuntu_lints: ^0.4.0
  ubuntu_provision_test: ^0.1.0
  ubuntu_test: ^0.2.2
  yaru_test: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
