name: subiquity_client
description: Subiquity Client
version: 0.1.0
homepage: https://github.com/canonical/subiquity_client.dart
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  package_config: ^2.1.0
  path: ^1.8.3
  synchronized: ^3.1.0
  ubuntu_logger: ^0.1.0
  xdg_directories: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: 5.4.2
  test: any
