name: subiquity_client
description: Subiquity Client
version: 0.1.0
homepage: https://github.com/canonical/subiquity_client.dart
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.10.0
  package_config: ^2.1.0
  path: ^1.8.3
  synchronized: ^3.1.0
  ubuntu_logger: ^0.1.1
  xdg_directories: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: 5.4.4
  test: any
  ubuntu_lints: ^0.3.0
