name: ubuntu_utils
description: Shared library for Ubuntu wizards.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.32.1"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  meta: ^1.11.0
  path: ^1.8.3
  ubuntu_localizations: ^0.5.2+2
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.1
  ubuntu_wizard: ^0.1.0
  url_launcher: ^6.2.5
  yaml: ^3.1.2
  yaru: ^8.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  plugin_platform_interface: ^2.1.8
  ubuntu_lints: ^0.4.0
  url_launcher_platform_interface: ^2.3.2
