name: ubuntu_utils
description: Shared library for Ubuntu wizards.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.9.1
  path: ^1.8.3
  safe_change_notifier: ^0.3.1
  ubuntu_localizations: ^0.3.3
  ubuntu_logger: ^0.1.0
  ubuntu_service: ^0.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.2
  plugin_platform_interface: ^2.1.6
  url_launcher_platform_interface: ^2.2.0
