name: landscape_client
description: Dart client for the Landscape Magic Attach service
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.1"
dependencies:
  grpc: ^4.0.1
  landscape_stubs: ^0.0.1
dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: any
