name: ubuntu_init
description: Ubuntu Init
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.2"

dependencies:
  args: ^2.4.2
  barcode_widget: ^2.0.4
  collection: ^1.17.0
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  form_field_validator: ^1.1.0
  gsettings: ^0.2.8
  handy_window: ^0.4.0
  intl: ^0.18.1
  meta: ^1.11.0
  path: ^1.8.3
  pdfrx: ^1.0.52
  provd_client: ^0.1.0
  stdlibc: ^0.1.4
  sysmetrics: ^0.1.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: 5af6896c75b5ab8f78b93f7f358836a8c4c7857f
  ubuntu_flavor: ^0.4.0
  ubuntu_localizations: ^0.3.5
  ubuntu_logger: ^0.1.1
  ubuntu_provision: ^0.1.0
  ubuntu_service: ^0.3.1
  ubuntu_session: ^0.0.4
  ubuntu_utils: ^0.1.0
  ubuntu_widgets: ^0.4.0
  ubuntu_wizard: ^0.1.0
  yaru: 4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.4
  translations_cleaner: ^0.0.5
  ubuntu_lints: ^0.3.0
  ubuntu_provision_test: ^0.1.0
  ubuntu_test: ^0.1.0-beta.8
  yaru_test: ^0.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/
