name: ubuntu_init
description: Ubuntu Init
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  args: ^2.4.2
  collection: ^1.17.0
  crypt: ^4.3.1
  dartx: ^1.2.0
  dbus: ^0.7.8
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  gsettings: ^0.2.8
  handy_window: ^0.3.1
  meta: ^1.9.1
  stdlibc: ^0.1.4
  sysmetrics: ^0.1.0
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
      ref: 5af6896c75b5ab8f78b93f7f358836a8c4c7857f
  ubuntu_flavor: ^0.2.0
  ubuntu_localizations: ^0.3.3
  ubuntu_logger: ^0.1.0
  ubuntu_provision: ^0.1.0
  ubuntu_service: ^0.2.2
  ubuntu_session: ^0.0.4
  ubuntu_utils: ^0.1.0
  ubuntu_wizard: ^0.1.0
  xdg_locale: ^0.0.1
  yaru: ^1.1.0
  yaru_icons: ^2.2.2
  yaru_widgets: ^3.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  ubuntu_lints:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_lints
      ref: main
  ubuntu_provision_test: ^0.1.0
  ubuntu_test: ^0.1.0-0
  yaru_test: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/kbds/
